name: catage
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+34

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.11.10
  cloud_firestore:
  firebase_core:
  #google_ml_kit: ^0.13.0
  #awesome_notifications:
  chat_bubbles: ^1.0.0+3
  hexcolor: ^2.0.3
  line_icons: ^2.0.1
  grouped_list: ^5.1.2
  group_list_view: ^1.1.1
  carousel_slider: ^2.2.1
  google_fonts: ^2.1.0
  flutter_launcher_name: ^0.0.1
  easy_localization: ^3.0.0
  flutter_slidable: ^3.0.0
  material_dialogs:
  lottie: ^2.1.0
  whatsapp_unilink: ^2.1.0
  flutter_svg: ^0.22.0
  page_transition: ^1.1.6
  responsive_sizer: 3.0.4+4
  flutter_scalable_ocr: ^1.0.1
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  shared_preferences: ^2.0.15
  date_time_picker: ^2.1.0
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  flutter_google_places: ^0.3.0
  map_launcher: ^3.1.0
  url_launcher:
  http: ^0.13.4
  email_validator: '^2.1.16'
  go_router: 6.2.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #flutter_local_notifications: 
  google_sign_in: ^5.4.2
  get: ^4.6.5
  sign_in_with_apple: ^4.3.0
  quick_actions: ^0.4.0+8
  icofont_flutter: ^1.4.0
  flutter_rating_bar: ^4.0.1
  mailer: ^6.1.0
  qr_flutter: ^4.0.0
  firebase_core_platform_interface: 4.5.1
  rflutter_alert: ^2.0.4
  firebase_messaging: ^13.0.4

dev_dependencies:
  #change_app_package_name: ^0.1.2
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Cat Life"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/banner-1.svg
    - images/banner-2.svg
    - images/banner-3.svg
    - images/logo.svg
    - images/logo.png
    - images/bannerDoctor.png
    - images/bannerHome.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
