// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2k08WU3gjfv-asc6jFEki0IDeLKHRvzM',
    appId: '1:477759819895:web:18490ab70c0fcf71697672',
    messagingSenderId: '477759819895',
    projectId: 'catlife-ae128',
    authDomain: 'catlife-ae128.firebaseapp.com',
    storageBucket: 'catlife-ae128.appspot.com',
    measurementId: 'G-547R2KFNMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Ay6ZjnOSvp5gpOl6PMOnS91caNVslfo',
    appId: '1:477759819895:android:c57443870779aa5a697672',
    messagingSenderId: '477759819895',
    projectId: 'catlife-ae128',
    storageBucket: 'catlife-ae128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBSLtAFqzfVi3X65FDL_9xI9E29a5ZSRs',
    appId: '1:477759819895:ios:ca2d8c5b3b85730f697672',
    messagingSenderId: '477759819895',
    projectId: 'catlife-ae128',
    storageBucket: 'catlife-ae128.appspot.com',
    androidClientId: '477759819895-1fr29nk5md5dl6fhqrj54p6n1dnr4h47.apps.googleusercontent.com',
    iosClientId: '477759819895-aslheah6lgap959j0qgu2rtaj90epic8.apps.googleusercontent.com',
    iosBundleId: 'com.example.catage',
  );
}
